services:
  - name: cancer-detection-app
    project: cancer-detection-app
    image: python:3.8
    build_command: pip install -r requirements.txt
    run_command: python app.py
    http_port: 5000
    routes:
      - path: /
    envs:
      - key: PORT
        value: "5000"
